site:
  title: demo docs
  start_page: home::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    start_path: home
  - url: ~/using
    branches: HEAD
  - url: ~/quickstart
    branches: HEAD
ui:
  bundle:
   url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable 
   snapshot: true
asciidoc:
  attributes: 
    toc: right
    external-link: '&raquo;'
    ddf-branding: DDF
    branding: DDF
    admin-console: Admin Console
    secure_url: https://localhost:8993
    download-url: https://github.com/codice/ddf   
    home_directory: \https://localhost:8993
    catalog-ui: Intrigue
    branding-lowercase: ddf
    command-console: Command Console 
    ddf-catalog: Catalog
